config/routes.rb
WashINSA::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'home#index'
  devise_for :user,
             path: '',
             :path_names => {:sign_in=>'login',:sign_out=>'logout',:sign_up=>'register'},
             :controllers => {
                 :registrations => 'registrations',
                 :omniauth_callbacks => "user/omniauth_callbacks"
             }
  get 'logout' => 'home#logout'
  resources :users
  resources :booking do
    get 'ask' => 'booking#ask_for'
  end
  get 'bookings(/:year/:month/:day)' => 'booking#index', :as => :bookings_on
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  belongs_to :user
  belongs_to :machine
  belongs_to :laundrette
  belongs_to :building

  scope :on_day, ->(day){where('start>?',day).where('start<?',day+1.day)}

end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  before_filter :authenticate_user!
  before_filter :user

  def index
    unless check_current_user!
      flash[:error] = "Enregistrer votre profil avant d'essayer de réserver"
      redirect_to edit_registration_path(current_user)
      return
    end
    defaults = {building:current_user.building_id,year: Time.now.year, month: Time.now.month, day:Time.now.day}
    params.replace(defaults.merge(params))
    @start=Time.new(params['year'].to_i,params['month'].to_i,params['day'].to_i,0,0,0)
  end

  def destroy
    if !booking.nil? and can? :destroy, booking
      booking.destroy!
    else
      flash[:error] = "Bien essayé ! Mais vous ne pouvez pas supprimer une réservation d'un autre."
    end
    redirect_to :booking_index
  end

  def new
    @start = Time.parse(params[:start])
    if can? :book, get_machine and is_not_booking_in_past? @start
        Booking.create! :user=>current_user, :machine=> get_machine, :start=>params[:start], :end=>Time.parse(params[:start])+1.hours
        flash[:notice] = 'Tout est bon'
    elsif !is_not_booking_in_past? @start
      flash[:error] = 'On ne peut pas réserver dans le passé ! (by: Capitain Obvious)'
    elsif !current_user.can_book?
      flash[:error] = 'Vous ne pouvez pas réserver plus de '+User.max_bookings.to_s+' crénaux'
    else
      flash[:error] = 'Vous ne pouvez pas réserver cette machine (problème technique)'
    end
    redirect_to :booking_index
  end

  private

  def is_not_booking_in_past?(time)
    (Time.now - 1.hours) <= time
  end

  def booking
    if params[:id].nil?
      nil
    else
      Booking.where(:id=>params[:id]).first
    end
  end

  def check_current_user!
    @user.laundrette_id != nil && @user.room_id != nil
  end

  def user
    @user = current_user
  end

  def get_machine
    if params[:machine].nil?
      nil
    else
      Machine.where(:id=> params[:machine]).first
    end
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/views/booking/index.html.erb
<div class="clearfix">
    <div class="pull-left"><h2><%= current_user.laundrette.name %></h2></div>
    <div class="btn-group pull-right">
        <%= link_to '<', bookings_on_url(:day=>(@start-1.day).day,:year=>(@start-1.day).year,:month=>(@start-1.day).month), {class: %w(btn btn-primary)} %>
        <div class="btn btn-primary"><%= I18n.localize @start.to_date, :format =>  '%A %d %B %Y'%></div>
        <%= link_to '>', bookings_on_url(:day=>(@start+1.day).day,:year=>(@start+1.day).year,:month=>(@start+1.day).month), {class: %w(btn btn-primary)} %>
     </div>
</div>

<div class="clearfix"></div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
          <th style="width: 20px">H</th>
          <% current_user.machines.each do |machine|%>
            <th><%= machine.name %></th>
          <% end %>
        </tr>
    </thead>
    <tbody>
        <% (7..23).each do |h| %>
            <tr>
              <td><%= h %></td>
              <% current_user.machines.each do |machine| %>
                  <td>
                    <% if machine.bookings.where(:start => @start + h.hours).first.nil? %>
                        <% if can? :book, machine and (Time.now - 1.hours) <= ((@start + (h).hours))%>
                            <%= link_to 'Réserver', new_booking_url({machine: machine.id, start: @start+h.hours}) %>
                        <% end %>
                    <% else %>
                        <% booking = machine.bookings.where(:start => @start + h.hours).first %>
                        <%= booking.user.name %>
                        <% if booking.user == current_user and booking.start > (Time.now-1.hour) %>
                            <%= link_to('(Annuler)', booking, :method => :delete)  %>
                        <% end %>
                <%  end %>
                   </td>
            <% end %>
            </tr>
        <% end %>
    </tbody>
</table>