config/routes.rb
WashINSA::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'home#index'
  devise_for :user,
             path: '',
             :path_names => {:sign_in=>'login',:sign_out=>'logout',:sign_up=>'register'},
             :controllers => {
                 :registrations => 'registrations',
                 :omniauth_callbacks => "user/omniauth_callbacks"
             }
  get 'logout' => 'home#logout'
  resources :users
  resources :booking do
    get 'ask' => 'booking#ask_for'
  end
  get 'bookings(/:year/:month/:day)' => 'booking#index', :as => :bookings_on
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 2.3 %>
<% if user_signed_in? %>
<div class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Laveries INSA</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav"></ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Mon compte', edit_user_url(current_user) %></li>
          <li><%= link_to 'Log out', destroy_session_url(current_user), :method => :delete %></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wash Insa" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Wash Insa' %>">
    <!-- Latest compiled and minified CSS
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">-->

    <!-- Optional theme
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">-->

    <!-- Latest compiled and minified JavaScript
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <% if user_signed_in? %>
            <div class="content">
              <div class="row">
                <div class="span12">
                  <%= render 'layouts/messages' %>
                  <%= yield %>
                </div>
              </div>
              <footer>
              </footer>
            </div>
         <% else %>
            <div class="content">
              <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                  <%= yield %>
                </div>
                <div class="col-md-4"></div>
              </div>
              <footer>
              </footer>
            </div>
         <%end%>

      </div>
    </main>
  </body>
</html>